// src/constants/cartConstants.js

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const FETCH_CART_ITEMS_REQUEST = 'FETCH_CART_ITEMS_REQUEST';
export const FETCH_CART_ITEMS_SUCCESS = 'FETCH_CART_ITEMS_SUCCESS';
export const FETCH_CART_ITEMS_FAIL = 'FETCH_CART_ITEMS_FAIL';

export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS';
export const FETCH_CART_ITEMS_FAILURE ='FETCH_CART_ITEMS_FAILURE'
export const GET_CART_ITEMS='GET_CART_ITEMS'

export const SET_CART_ITEMS_COUNT  ='SET_CART_ITEMS_COUNT '
export const  FETCH_CART_REQUEST ='FETCH_CART_REQUEST';
export const  FETCH_CART_SUCCESS ='FETCH_CART_SUCCESS';
export const    FETCH_CART_FAILURE='  FETCH_CART_FAILURE'

export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const FETCH_WISH_ITEMS = "FETCH_WISH_ITEMS";
export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";
export const UPDATE_WISH_ITEMS = "UPDATE_WISH_ITEMS";